version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - app-network
    env_file:
      - .env

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - redis
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
